# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

PreCommit:
  ALL:
    on_warn: fail

  # Not required because it's not needed/sensible in a CI context.
  AuthorEmail:
    enabled: true
    required: false

  # Not required because it's not needed/sensible in a CI context.
  AuthorName:
    enabled: true
    required: false

  BundleCheck:
    description: 'Check if local Gemfile.lock matches Gemfile when either changes.'
    enabled: true

  BundleAudit:
    description: 'Checks for vulnerable versions of gems in Gemfile.lock.'
    enabled: true
    command: ['bundle', 'exec', 'bundle-audit']
    flags: ['--update']

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']

  Fasterer:
    enabled: true
    command: ['bundle', 'exec', 'fasterer']

  Brakeman:
    enabled: true
    command: ['brakeman']
    flags: ['-A']

  YarnAudit:
    description: 'Checks for vulnerable versions of packages in yarn.lock.'
    enabled: true
    command: ['yarn', 'audit']

  EsLint:
    enabled: true
    required_executable: './node_modules/.bin/eslint'
    command: ['yarn', 'lint']

  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rake', 'parallel:spec']
